version: '3.1'

services:

  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./www:/usr/share/nginx/html

volumes:
  nginx:
